In [3]:
#Scope Variables

b = 10
def g():
    a = 9 #local par rapport à g
    # print = 9 # builtin
    print(a, b) # Local à la fonction
    def f():
        print(a) # E
        print(b) # localment b ? englobant b ? global b ? 

    f()

g()

9 10
9
10


In [4]:
#Conditions

x = 7

if x > 10:
    print("x est grand")
elif x > 5:
    print("x est moyen")
else:
    print("x est petit")

x est moyen


In [5]:
#Lists

fruits = ["pomme", "banane", "kiwi"]
fruits.append("orange")
fruits[1] = "fraise"
print(fruits)

['pomme', 'fraise', 'kiwi', 'orange']


In [1]:
#La liste élevée au carrée on a une liste de 5 valeurs consécutives de 1 à 5

#Compréhension de liste
l = [ i**2 for i in range(1,6) ] 
print(l)

[1, 4, 9, 16, 25]


In [2]:
l[:2]

[1, 4]

In [3]:
l[1::2]

[4, 16]

In [4]:
l[0:2:1]

[1, 4]

In [5]:
l[0:2:2]

[1]

In [6]:
l[:4]

[1, 4, 9, 16]

In [7]:
l[::-1]

[25, 16, 9, 4, 1]

In [8]:
l[::-2]

[25, 9, 1]

In [17]:
import numpy as np

In [18]:
a = np.array([1, 2, 3])

print(a)          # [1 2 3]
print(a.shape)    # (3,)

[1 2 3]
(3,)


In [19]:
a = np.array([1, 2, 3])

a[0] = 3



In [20]:
a

array([3, 2, 3])

In [21]:
type(a)

numpy.ndarray

In [22]:
a.dtype

dtype('int64')

In [23]:
b = np.array(["Bonjour", "Tout le monde"], dtype='<U2')

In [24]:
b

array(['Bo', 'To'], dtype='<U2')

In [25]:
(a*2 - 10*a)**2

array([576, 256, 576])

In [26]:
np.median(a)

np.float64(3.0)

In [3]:
import pandas as pd #pandas repose sur numpy analyse de données et stat outil indispensable du data analyste

In [6]:
#Series & DataFrame

s = pd.Series([10, 20, 30], index=["a", "b", "c"])

#Stat des séries
s.describe()

count     3.0
mean     20.0
std      10.0
min      10.0
25%      15.0
50%      20.0
75%      25.0
max      30.0
dtype: float64

In [27]:
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, np.nan, 35]
})

print(df.shape)
df

(3, 2)


name   age
0    Alice  25.0
1      Bob   NaN
2  Charlie  35.0

In [28]:
#Mask the booleans and transform in a table

mask = df ["age"] > 25

df[mask]

name   age
2  Charlie  35.0

In [29]:
df ["sex"] = ["F", "M", "M"]

df

name   age sex
0    Alice  25.0   F
1      Bob   NaN   M
2  Charlie  35.0   M

In [30]:
#Add a new row

df.loc[3] = ["Roxy", 33, "F"]

df

name   age sex
0    Alice  25.0   F
1      Bob   NaN   M
2  Charlie  35.0   M
3     Roxy  33.0   F

In [31]:
df.shape

(4, 3)

In [32]:
df.isna()

name    age    sex
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False  False

In [33]:
#Atleast one is true = 0 columns

df.isna().any(axis=0)

name    False
age      True
sex     False
dtype: bool

In [34]:
#Axis on the columns
df.isna().any(axis=1)


0    False
1     True
2    False
3    False
dtype: bool

In [38]:
#List only the row with the value NaN

mask = df.isna().any(axis=1)

df[mask]

name  age sex
1  Bob  NaN   M

In [39]:
# ~ For the contrary negative in binary

df[~mask]

name   age sex
0    Alice  25.0   F
2  Charlie  35.0   M
3     Roxy  33.0   F

In [40]:
#Use to transpose 

df.T

0    1        2     3
name  Alice  Bob  Charlie  Roxy
age    25.0  NaN     35.0  33.0
sex       F    M        M     F

In [41]:
df.T.isna().any(axis=1)

name    False
age      True
sex     False
dtype: bool

In [43]:
df.T[df.T.isna().any(axis=1)].T

age
0  25.0
1   NaN
2  35.0
3  33.0

In [46]:
mask = ~(df.T.isna().any(axis=1) )

df.T[mask].T

name sex
0    Alice   F
1      Bob   M
2  Charlie   M
3     Roxy   F

In [10]:
#Download data

titanic = pd.read_csv("./titanic.csv")

#List the first five
titanic.head()
#print(titanic.columns)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [14]:
#Rename a column

titanic.rename(columns = {"PassengerId" : "PassengerID"})

#Delete columns

#titanic.drop(columns = ["Ticket", "Fare", "Cabin", "Embarked"], inplace=True)
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch  
0      0  
1      0  
2      0  
3      0  
4      0

In [15]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp       Parch
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000